# Generated by Django 5.2.14 on 2026-05-14 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('short_description', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('developer', models.CharField(max_length=200)),
                ('genre', models.CharField(max_length=200)),
                ('platform', models.CharField(max_length=200)),
                ('python_version', models.CharField(max_length=200)),
                ('pygame_version', models.CharField(max_length=200)),
                ('download_url', models.URLField()),
                ('source_code_url', models.URLField()),
                ('instructions', models.TextField(max_length=200)),
                ('featured', models.CharField(max_length=200)),
                ('download_count', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(max_length=200)),
                ('updated_at', models.DateTimeField(max_length=200)),
            ],
        ),
    ]
