# Generated by Django 5.2.14 on 2026-05-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to='downloads/'),
        ),
        migrations.AddField(
            model_name='game',
            name='screenshots',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
