# Generated by Django 5.2.14 on 2026-06-03 03:04

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_game_download_file_game_screenshots_game_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='download_file',
            field=models.FileField(blank=True, null=True, upload_to=main.utils.name_changer_downloads),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.CharField(choices=[('plataforma', 'Plataforma'), ('arcade', 'Arcade'), ('corrida', 'Corrida'), ('luta', 'Luta'), ('tiro', 'Tiro'), ('aventura', 'Aventura'), ('rpg', 'Rpg'), ('estrategia', 'Estrategia'), ('puzzle', 'Puzzle'), ('labirinto', 'Labirinto'), ('survival', 'Survival'), ('roguelike', 'Roguelike'), ('tower_defense', 'Tower Defense'), ('simulacao', 'Simulacao'), ('esporte', 'Esporte'), ('cartas', 'Cartas'), ('tabuleiro', 'Tabuleiro'), ('quiz', 'Quiz'), ('idle', 'Idle'), ('clicker', 'Clicker'), ('ritmo', 'Ritmo'), ('stealth', 'Stealth'), ('metroidvania', 'Metroidvania'), ('hack_and_slash', 'Hack And Slash'), ('bullet_hell', 'Bullet Hell'), ('endless_runner', 'Endless Runner'), ('snake', 'Snake'), ('breakout', 'Breakout'), ('pong', 'Pong'), ('space_shooter', 'Space Shooter')], max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshots',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.name_changer_imagens),
        ),
        migrations.AlterField(
            model_name='game',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.name_changer_thumbnails),
        ),
    ]
