# Generated by Django 5.2.14 on 2026-06-11 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_game_instructions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='download_count',
            field=models.CharField(blank=True, default='0', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='download_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='featured',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='pygame_version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='python_version',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='short_description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='game',
            name='source_code_url',
            field=models.URLField(blank=True),
        ),
    ]
