# Generated by Django 5.2.14 on 2026-06-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_game_description_alter_game_download_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='download_count',
            field=models.IntegerField(default=0),
        ),
    ]
